# Generated by Django 4.2.4 on 2023-08-22 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="customer_id",
            new_name="customer",
        ),
    ]
