# Generated by Django 4.2.4 on 2023-08-17 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
