# Generated by Django 4.2.4 on 2023-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
