# Generated by Django 4.2.4 on 2023-08-24 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_customer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user",
            new_name="customuser",
        ),
    ]
