# Generated by Django 4.2.4 on 2023-08-24 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_rename_user_customer_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="customuser",
        ),
        migrations.AddField(
            model_name="customer",
            name="customuser",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
