# Generated by Django 4.2.4 on 2023-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_remove_customer_user_customer_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="customer",
        ),
        migrations.AddField(
            model_name="product",
            name="customer",
            field=models.ManyToManyField(default=None, to="inventory.customer"),
        ),
    ]
