# Generated by Django 4.2.4 on 2023-08-24 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_remove_product_customer_product_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="customuser",
        ),
        migrations.AddField(
            model_name="customer",
            name="customuser",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
